version: '3.7'

services:
  kovalskaya_db:
    container_name: kovalskaya_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:16.1-alpine
